import './globals.css'

export const metadata = {
  title: 'Productivity Tool',
  description: 'Generated by Team',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className = "bg-gray-500/5">{children}</body>
    </html>
  )
}
